services:
  sqs:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
    environment:
      - ELASTICMQ_OPTS=-Dconfig.file=/opt/elasticmq.conf
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf



  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=1A!2@b3%c4d5e6f7g8h9i0j
      # - plugins.security.disabled=true
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"


#  activemq:
#    image: 'apache/activemq-classic:latest'
#    ports:
#      - '61616'
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
