services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - DEBUG=1
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

  opensearch:
    image: opensearchproject/opensearch:latest
    platform: linux/arm64
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=1A!2@b3%c4d5e6f7g8h9i0j
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:latest
#    environment:
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0
#      - CLI_JAVA_OPTS=-XX:UseSVE=0
#      - node.name=elasticsearch
#      - cluster.name=es-vic-local
#      - discovery.type=single-node
#      - cluster.routing.allocation.disk.threshold_enabled=false
#      - xpack.security.enabled=false
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

#  activemq:
#    image: 'apache/activemq-classic:latest'
#    ports:
#      - '61616'
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5672'
